name: afia
favicon: null
layout_spectrum: 0.37150501017458737
typography_spectrum: 0.3172210957854986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5722a'
    - '#ffb68f'
    - '#f9e5c7'
    - '#ee9d70'
  brandStrength: 0.5726504398044199
  lightness: 0.06881229463033378
  saturation: 0.3764339897315949
  rhythmicContrast: 0.3248025111388415
purpose: []
